# Generated by Django 6.0.6 on 2026-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='payout_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='number_of_assets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
