# Generated by Django 6.0.6 on 2026-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_payout_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
