# Generated by Django 6.0.6 on 2026-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_duration_months_investment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
