# Generated by Django 6.0.6 on 2026-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investment_management_fee_investment_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
