# Generated by Django 6.0.6 on 2026-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttier',
            name='multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Price multiplier e.g. Standard=1, Premium=2'),
        ),
    ]
