# Generated by Django 6.0.6 on 2026-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_investmenttier_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='asset_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
