# Generated by Django 6.0.6 on 2026-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_investment_asset_type_investment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='roi_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual ROI % set by admin on activation', max_digits=5, null=True),
        ),
    ]
