# Generated by Django 6.0.6 on 2026-06-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_investment_roi_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='roi_rate',
        ),
        migrations.RemoveField(
            model_name='investmenttier',
            name='multiplier',
        ),
    ]
