# Generated by Django 6.0.6 on 2026-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_remove_investment_roi_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
