# Generated by Django 6.0.6 on 2026-06-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('investments', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='investments.investment'),
        ),
        migrations.AlterUniqueTogether(
            name='assetallocation',
            unique_together={('investment', 'asset')},
        ),
    ]
