# Generated by Django 6.0.6 on 2026-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Management fee for this asset', max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time service charge for this asset', max_digits=15),
        ),
    ]
