# Generated by Django 6.0.6 on 2026-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_management_fee_asset_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_value',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
