# Generated by Django 6.0.6 on 2026-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_current_value_alter_asset_asset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
