# Generated by Django 6.0.6 on 2026-06-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetallocation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='hirer_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='hirer_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
