# Generated by Django 6.0.6 on 2026-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetallocation_hirer_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetallocation',
            old_name='hirer_paid',
            new_name='current_period_paid',
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='hirer_paid_at',
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='hirer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='hirer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
