# Generated by Django 6.0.6 on 2026-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_hirer_paid_assetallocation_current_period_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='weekly_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
