# Generated by Django 6.0.6 on 2026-06-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_duration_weeks_asset_weekly_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='paystack_page_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='paystack_payment_link',
            field=models.URLField(blank=True),
        ),
    ]
