# Generated by Django 6.0.6 on 2026-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
