# Generated by Django 6.0.6 on 2026-06-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0010_remove_investment_roi_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer_name', models.CharField(max_length=200)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('partial', 'Partial'), ('missed', 'Missed')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payout_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='investments.investment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
