# Generated by Django 6.0.6 on 2026-06-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_hirer_paid_assetallocation_current_period_paid_and_more'),
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='assets.assetallocation'),
        ),
    ]
